### PR TITLE
Move all string function to special class.

### PR DESCRIPTION
**Pull request by rusan**
mbstring.func_overload not possible to change in runtime and in this case on all systems, where string function overloaded not possible request auth sms - it will be 'no_routes' error (there is different result of  strtolower and mb_strtolower after openssl_random_pseudo_bytes).

### CODE REVIEW

**Comment by 0xTryCatch** [comment]
What exactly does this commit fix? I do see that it introduces new bugs because not all str* functions must be replaced with their mbstr* counterparts

**Comment by rusan** [comment]
For example - if (init_set('mbstring.func_overload') & 2) == true, then no possible to requestCode from whatsapp - always return error 'no_routes'.

**Comment by rusan** [comment]
This code makes that all used string function works like string function (not mb string functions)

**Comment by 0xTryCatch** [comment]
Well, the real solution here is to disable the ```mbstring.func_overload``` setting locally. And besides that this pull request also introduces new bugs so it is not possible to merge it unfortunately.

**Comment by rusan** [comment]
Some times this is impossible to disable mbstring.func_overload setting localy. For example - all other huge project works with this settings.

**Pull request closed without merging**
