### PR TITLE
Token update

### PR DESCRIPTION
**Pull request by 0xTryCatch**

### CODE REVIEW

**Comment by for2ne** [comment]
@0xTryCatch,  Why not use one of the latest version? For example, I use 2.16.15 (xo27hUuxYWCTv0HFuxR53g==) and all work fine. or may be problems?

**Comment by elchobo5** [comment]
when tested with the token...

get response:

class stdClass#13 (2) {
  public $status =>
  string(4) "fail"
  public $reason =>
  string(9) "bad_token"
}

**Comment by edudesouza** [comment]
Wich version did you try?

Sent using CloudMagic Email [https://cloudmagic.com/k/d/mailapp?ct=pa&cv=8.4.33&pv=4.3&source=email_footer_2] On Thu, Apr 21, 2016 at 6:11 PM, elchobo5 < notifications@github.com [notifications@github.com] > wrote:
when tested with the token...

get response:

class stdClass#13 (2) {
public $status =>
string(4) "fail"
public $reason =>
string(9) "bad_token"
}

**Comment by elchobo5** [comment]
const WHATSAPP_VER = '2.12.556';  
const WHATSAPP_USER_AGENT = 'WhatsApp/2.12.556 Android/4.3 Device/Xiaomi-HM_1SW';  
$classesMd5 = 'ry9Xz6kVioQctwA3G9z62Q==';

I'm missing something?

**Pull request merged**
