### PR TITLE
add docker in order to quickly setup envrionment

### PR DESCRIPTION
**Pull request by Shaked**
This commit adds support for docker. I have noticed that many people are having a hard time to install the dependencies and figure out how to setup everything before being able to run and receive a message using Chat-API. 

If approved, would be nice to add it to the Wiki as well. 

Thank you for the great repository, 
Shaked

### CODE REVIEW

**Comment by natsu90** [comment]
I would prefer this PR to be a different repo.

**Comment by Shaked** [comment]
I was actually thinking about the exact thing yesterday. I will do it later
today and maybe you could just link it via README & Wiki?

All the best


__________________
Shaked Klein Orbach
http://www.shakedos.com/about

**Comment by Shaked** [comment]
I have created a new repository: https://github.com/Shaked/docker-whatsapp

**Comment by mgp25** [comment]
@Shaked i'll add it in the wiki

Thanks

**Pull request closed without merging**
