### PR TITLE
Image Upload Issue: Undefined offset: 1 list($header, $body) = preg_split("/\R\R/", $data…

### PR DESCRIPTION
**Pull request by v920749**
…, 2);

Perhaps a recent change in whatsapp service caused broken image uploads. This fixed the issue.

### CODE REVIEW

**Comment by v920749** [comment]
@alesantosp Thanks, even though it worked with one addition. I have updated this PR with your feedback.

**Comment by v920749** [comment]
@alesantosp I have incorporated your suggestion.

**Comment by styler2go** [comment]
Adding two `$data .= fgets($sock, 8192);` fixed it for me too. Thank you!

**Comment by v920749** [comment]
@styler2go  Your welcome.

**Pull request closed without merging**
