### PR TITLE
Fixed error caused by missing "key" or chainKey does not exist

### PR DESCRIPTION
**Pull request by billywcl**

### CODE REVIEW

**Comment by mgp25** [comment]
@billywcl can you post context and when it happens with a node?

**Comment by billywcl** [comment]
When I have it happened again, I will record it and make another request.

**Comment by mgp25** [comment]
@billywcl does your fix works fine? it decrypts and everything fine? If all tests passed, feel free to re-open and i'll merge it

Regards

**Comment by billywcl** [comment]
yes, if the SenderChain does not exist, it send plain text, otherwise encrypted message.

**Comment by Andrw999** [comment]
Hi I'm new in this php  world, I what to test it by sending message to one number to another using this command in Ubuntu 15 console:

php -r "require 'vendor/whatsapp/chat-api/examples/exampleFunctional.php'; sendMessage('Hola');"

As I said I'm new doing this kind of things I edited this files: whatsapp.php, Simple CLI client.php, exampleFunctional.php and exampleRegister.php, I know that this is something very easy but I'm kind of new with php thanks in advance.

**Comment by 0xTryCatch** [comment]
Again, no programming advice here

**Pull request closed without merging**
