### PR TITLE
Fixed error caused by missing "key" child node and SenderChain does not exist

### PR DESCRIPTION
**Pull request by billywcl**

### CODE REVIEW

**Comment by mgp25** [comment]
@billywcl we should always send encrypting the message

**Comment by billywcl** [comment]
I see, do you have any idea why this happens?

**Comment by mgp25** [comment]
@billywcl im not exactly sure, i have to research it, but we should avoid as much as possible plaintext messages

**Comment by mgp25** [comment]
@billywcl this is caused when trying to send a message to an invalid number

Regards

**Comment by mgp25** [comment]
@billywcl added this commit in the next Chat API relase

Regards

**Pull request closed without merging**
